config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  resource :profile, only: %i(show edit update)

  resources :recipes, only: %i(index show)
  resources :ingredients

  namespace :users do
    resources :recipes, only: %i(new create edit update destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe, through: :recipes_ingredients

  validates :title, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend Enumerize

  AVAILABLE_STATUSES = %w(pending denied moderating approved).freeze

  enumerize :status, in: AVAILABLE_STATUSES, predicates: true, default: :pending

  belongs_to :author, class_name: "User"

  has_many :ingredient, through: :recipes_ingredients

  validates :title, :content, presence: true
  validates :title, length: { minimum: 3 }
end

app/models/recipes_ingredient.rb
class RecipesIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :recipe, :ingredient, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  ADMIN_ROLES = %w(manager moderator coordinator).freeze
  AVAILABLE_ROLES = ADMIN_ROLES

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :invitable

  has_many :recipes, foreign_key: :author_id

  enumerize :roles, in: AVAILABLE_ROLES, multiple: true, predicates: true

  validates :email, presence: true
  validates :email, :login, uniqueness: true
  validates :login, presence: true, if: :accepted_or_not_invited?

  scope :admin, -> { where("roles && ARRAY[?]::varchar[]", ADMIN_ROLES) }

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def admin?
    manager? || moderator? || coordinator?
  end

  def role
    roles.join(", ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  expose :ingredient
  expose :ingredients, -> { Ingredient.all }

  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def create
    if ingredient.save
      redirect_to ingredient_path(ingredient)
    else
      render :new
    end
  end

  def update
    if ingredient.update(ingredient_params)
      redirect_to ingredient_path(ingredient)
    else
      render :new
    end
  end

  def destroy
    ingredient.destroy

    redirect_to ingredients_url, notice: "Ingredient was successfully destroyed."
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:title)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end

  def edit
  end

  def update
    if current_user.update(users_params)
      redirect_to profile_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def users_params
    params.require(:user).permit(:email, :avatar)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  expose :recipe

  def index
  end

  def show
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    before_action :authenticate_user!, :authorize_resource!
  end
end

app/controllers/users/invitations_controller.rb
module Users
  class InvitationsController < Devise::InvitationsController
    before_action :configure_permitted_parameters
    before_action :authenticate_user!, :authorize_resource!, only: %i(new create)

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:accept_invitation, keys: %i(login))
      devise_parameter_sanitizer.permit(:invite, keys: [:first_name, :last_name, { roles: [] }])
    end

    def authorize_resource!
      authorize! current_user, with: InvitationPolicy
    end
  end
end

app/controllers/users/recipes_controller.rb
module Users
  class RecipesController < BaseController
    expose :recipe

    def new
    end

    def create
      if create_recipe.success?
        redirect_to recipe_path(recipe)
      else
        render :new
      end
    end

    def edit
    end

    def update
      if recipe.save
        redirect_to recipe_path(recipe)
      else
        render :edit
      end
    end

    def destroy
      recipe.destroy
    end

    private

    def create_recipe
      ::CreateRecipe.call!(recipe: recipe)
    end

    def authorize_resource!
      authorize! recipe
    end

    def recipe_params
      params.require(:recipe).permit(:title, :content).merge(author: current_user)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i(login first_name last_name))
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def after_sign_in_path_for(_resource)
    current_user_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.slim
h1.text-center.mt-1
  | Добро пожаловать!

p.text-center.mt-1
  | Книга рецептов - сайт, где ты можешь найти рецепт

.container
  .row.justify-content-center
    = link_to "#", class: "btn btn-outline-info col-2 align-self-start mr-1 mb-2" do
      | по настроению
    = link_to "#", class: "btn btn-outline-info col-2 align-self-start mr-1 mb-2" do
      | по списку продуктов
    
p.text-center.mt-1
  | ... или воспользоваться нашим рандомайзером и найти

.container
  .row.justify-content-center
    = link_to "#", class: "btn btn-outline-info col-2 align-self-start mr-1 mb-2" do
      | рецепт дня
    = link_to "#", class: "btn btn-outline-info col-2 align-self-start mr-1 mb-2" do
      | меню дня
    

- if user_signed_in?
  .p.text-center.mt-1 А может быть Вы хотите добавить свой рецепт?

  .container
    .row.justify-content-center
      = link_to new_users_recipe_path, class: "btn btn-outline-info col-2 align-self-start mr-1 mb-2" do
        | добавить
- else
  .p.text-center.mt-1 Войдите, чтобы добавить рецепт

app/views/ingredients/_form.html.slim
= simple_form_for ingredient do |f|
  .form-group
    = f.input :title, autofocus: true

  .form-actions
    = f.submit class: "btn btn-primary"

app/views/ingredients/edit.html.slim
.page-header
  h1 Edit Ingredient
= render "form"

app/views/ingredients/index.html.slim
h1
  | All ingredients
- ingredients.each do |ingredient|
  h3
    = ingredient.title
  = link_to "Show", ingredient_path(ingredient)
  = link_to "Edit", edit_ingredient_path(ingredient)
  = link_to "Destroy", ingredient_path(ingredient), method: :delete, data: { confirm: "Are you sure?" }
  hr
= link_to "New ingredient", new_ingredient_path

app/views/ingredients/new.html.slim
.page-header
  h1 New Ingredient
= render "form"

app/views/ingredients/show.html.slim
h3
  = ingredient.title

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Cookbook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light.justify-content-between
      / = link_to root_path, class: "navbar-brand" do
      /   = image_tag "Icon-Small.png"
      /   span CookBook

      collapse.navbar-collapse#collapsibleNavbar
        ul.navbar-nav.mr-auto
          li.nav-item.dropdown
            #navbardrop
              = link_to "Рецепты", "#", class: "nav-link dropdown-toggle"
              / .droppdown-menu
              /   = link_to "Завтраки", "#", class: "dropdown-item"
              /   = link_to "Обеды", "#", class: "dropdown-item"
              /   = link_to "Ужины", "#", class: "dropdown-item"
          li.nav-item 
            = link_to "Статьи", "#", class: "nav-link"

      ul.navbar-nav.ml-auto
        - if user_signed_in?
          li.nav-item
            = button_to "Выйти", destroy_user_session_path, method: :delete, class: "btn btn-outline-info ml-sm-1"
          li.nav-item
            = link_to "Профиль", profile_path, class: "btn btn-outline-info ml-sm-1"
        - else
          li.nav-item
            = link_to "Войти", new_user_session_path, class: "btn btn-outline-info ml-sm-1"

    - if notice
      p.alert.alert-success
        = notice
    - if alert
      p.alert.alert-danger
        = alert
    = yield

app/views/profiles/edit.html.slim
.container
  = simple_form_for current_user, url: profile_path do |f|
    .form-group
      = f.input :email

    .form-group
      = f.input :login

    .form-actions
      = f.submit class: "btn btn-primary"

app/views/profiles/show.html.slim
.container
  h1.post-title.text-center.text-md-left
    = current_user.login
  hr.m-0.d-none.d-md-block

  .d-flex.align-items-center.py-2.text-right
    ul
      li
        = current_user.email
      li
        = current_user.first_name
      li
        = current_user.last_name
      - if current_user.admin?
        li
          = current_user.role

  .div
    = link_to "Избранное", "#", class: "btn btn-outline-secondary mt-md-2"
  .div
    = link_to "Добавить свой рецепт", new_users_recipe_path, class: "btn btn-outline-success  mt-md-2"
  .div
    = link_to "Мои рецепты", "#", class: "btn btn-outline-secondary mt-md-2"
  .div
    = link_to 'Редактировать профиль', edit_profile_path(current_user), class: "btn btn-outline-secondary mt-md-2"
  - if allowed_to?(:create?, current_user, with: Users::InvitationPolicy)
    .div
    = link_to 'Пригласить сотрудника', new_user_invitation_path, class: "btn btn-outline-secondary mt-md-2"

app/views/recipes/index.html.slim
h1 Recipes!

app/views/recipes/show.html.slim
.article.recipe-page.py-2
  .header
    .h2.post-title.text-center.text-md-left
      = recipe.title
    .hr.m-0.d-none.d-md-block
    .recipe-author.d-flex.justify-content-between.py-2.text-right
      .small
        | Автор рецепта
        =< link_to "#{recipe.author.login}", "#"
      - if allowed_to?(:edit?, recipe, with: Users::RecipePolicy)
        .small
          = link_to "Редактировать", edit_users_recipe_path(recipe)
      - if allowed_to?(:destroy?, recipe, with: Users::RecipePolicy)
          => link_to "Удалить", users_recipe_path(recipe), method: :delete, data: { confirm: "Are you sure?" }

  .card
    .p.text-left
      = recipe.content

app/views/users/invitations/edit.html.slim
h2
  = t "devise.invitations.edit.header"

= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f|
  = f.error_notification
  = f.hidden_field :invitation_token

  .form-inputs
    = f.input :login
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit, t("devise.invitations.edit.submit_button")

app/views/users/invitations/new.html.slim
h2
  = t "devise.invitations.new.header"

= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post } do |f|
  = f.error_notification

  .form-group
    = f.input :email

  .form-group
    = f.input :first_name

  .form-group
    = f.input :last_name

  .form-group
    = f.input :roles

  .form-actions
    = f.submit t("devise.invitations.new.submit_button")

app/views/users/recipes/_form.html.slim
= simple_form_for [:users, recipe] do |f|
  .form-group
    = f.input :title, autofocus: true

  .form-group
    = f.input :content, as: :text

  .form-actions
    = f.submit class: "btn btn-primary"

app/views/users/recipes/edit.html.slim
h3 Edit your recipe
= render "form"

app/views/users/recipes/new.html.slim
h3 Поделись своим рецептом
= render "form"